In [115]:
import collections
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.font_manager
from scipy.stats import ks_2samp
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [116]:
signal = pd.read_csv("resonances0.txt", delim_whitespace=True)

In [117]:
signal.shape, signal.head()

((300, 12),
     Z  El   A   Io      Bn     D0    dD    S0    dS    Gg   dG  Com.
 0  11  Na  23  1.5   6.960  100.0  20.0  0.25  0.15     -    -  *07I
 1  12  Mg  24  0.0   7.331  480.0  70.0  0.00  0.00     -    -  *07I
 2  12  Mg  25  2.5  11.094   50.0  10.0  0.00  0.00     -    -  *07I
 3  12  Mg  26  0.0   6.446  210.0  80.0  0.00  0.00     -    -  *07I
 4  13  Al  27  2.5   7.725   55.0   6.0  2.30  0.50  1600  400   07I)

In [118]:
pd.concat([signal.describe(include='all'), signal.dtypes.to_frame().T])


Z      El           A        Io        Bn         D0  \
count       300.0     300       300.0     300.0     300.0      300.0   
unique        NaN      83         NaN       NaN       NaN        NaN   
top           NaN      Sn         NaN       NaN       NaN        NaN   
freq          NaN       9         NaN       NaN       NaN        NaN   
mean    55.503333     NaN  134.586667      1.14  7.054117   9.802936   
std     22.893018     NaN   61.025154  1.581794  1.440705  42.435471   
min          11.0     NaN        23.0       0.0     3.937    0.00027   
25%         37.75     NaN        86.0       0.0   6.09975      0.014   
50%          56.0     NaN       134.0       0.0    6.7835     0.1025   
75%          72.0     NaN      178.25       2.5   7.83325        1.5   
max          98.0     NaN       252.0       9.0    11.627      480.0   
0           int64  object       int64   float64   float64    float64   

              dD        S0        dS      Gg      dG    Com.  
count      300.0     300.0     300.0     300     300     300  
unique       NaN       NaN       NaN     129      48      26  
top          NaN       NaN       NaN       -       -     96I  
freq         NaN       NaN       NaN      52      52      70  
mean    1.774252    1.4328    0.2777     NaN     NaN     NaN  
std     8.097214  1.229216  0.247061     NaN     NaN     NaN  
min      0.00002       0.0       0.0     NaN     NaN     NaN  
25%       0.0015     0.515       0.1     NaN     NaN     NaN  
50%        0.019       1.2       0.2     NaN     NaN     NaN  
75%        0.235       2.0       0.4     NaN     NaN     NaN  
max         80.0       7.1       1.5     NaN     NaN     NaN  
0        float64   float64   float64  object  object  object

In [125]:
x = signal[['Z','A']]
y = signal[['D0']]
arr_x = x.values.reshape(-1,2)
arr_y = y.values.ravel()
print(arr_x,arr_y)

[[ 11  23]
 [ 12  24]
 [ 12  25]
 [ 12  26]
 [ 13  27]
 [ 14  28]
 [ 14  29]
 [ 14  30]
 [ 15  31]
 [ 16  32]
 [ 16  33]
 [ 16  34]
 [ 17  35]
 [ 17  37]
 [ 18  40]
 [ 19  39]
 [ 19  41]
 [ 20  40]
 [ 20  42]
 [ 20  43]
 [ 20  44]
 [ 21  45]
 [ 22  46]
 [ 22  47]
 [ 22  48]
 [ 22  49]
 [ 22  50]
 [ 23  50]
 [ 23  51]
 [ 24  50]
 [ 24  52]
 [ 24  53]
 [ 24  54]
 [ 25  55]
 [ 26  54]
 [ 26  56]
 [ 26  57]
 [ 26  58]
 [ 27  59]
 [ 28  58]
 [ 28  59]
 [ 28  60]
 [ 28  61]
 [ 28  62]
 [ 28  64]
 [ 29  63]
 [ 29  65]
 [ 30  64]
 [ 30  66]
 [ 30  67]
 [ 30  68]
 [ 30  70]
 [ 31  69]
 [ 31  71]
 [ 32  70]
 [ 32  72]
 [ 32  73]
 [ 32  74]
 [ 32  76]
 [ 33  75]
 [ 34  74]
 [ 34  76]
 [ 34  77]
 [ 34  78]
 [ 34  80]
 [ 34  82]
 [ 35  79]
 [ 35  81]
 [ 36  78]
 [ 36  80]
 [ 36  83]
 [ 36  84]
 [ 36  86]
 [ 37  85]
 [ 37  87]
 [ 38  84]
 [ 38  86]
 [ 38  87]
 [ 38  88]
 [ 39  89]
 [ 40  90]
 [ 40  91]
 [ 40  92]
 [ 40  93]
 [ 40  94]
 [ 40  96]
 [ 41  93]
 [ 42  92]
 [ 42  94]
 [ 42  95]
 [ 42  96]

In [128]:
X_train, X_test, y_train, y_test = train_test_split(arr_x, arr_y, test_size=0.3, random_state=0)
print(X_train)
# X_train = X_train.values
# X_test = X_test.values
# y_train = y_train.values
# y_test = y_test.values

[[ 94 239]
 [ 28  64]
 [ 92 233]
 [ 64 155]
 [ 56 134]
 [ 57 139]
 [ 46 104]
 [ 32  70]
 [ 63 151]
 [ 20  42]
 [ 94 238]
 [ 78 198]
 [ 50 122]
 [ 60 150]
 [ 36  84]
 [ 73 180]
 [ 77 193]
 [ 68 166]
 [ 95 242]
 [ 70 172]
 [ 56 136]
 [ 58 136]
 [ 25  55]
 [ 40  93]
 [ 78 196]
 [ 34  74]
 [ 60 145]
 [ 93 238]
 [ 48 108]
 [ 21  45]
 [ 24  50]
 [ 55 133]
 [ 19  41]
 [ 32  73]
 [ 38  84]
 [ 48 106]
 [ 62 148]
 [ 66 164]
 [ 58 141]
 [ 13  27]
 [ 44 100]
 [ 60 144]
 [ 34  76]
 [ 35  81]
 [ 53 127]
 [ 66 161]
 [ 83 209]
 [ 93 237]
 [ 28  59]
 [ 91 231]
 [ 17  37]
 [ 47 107]
 [ 71 176]
 [ 12  26]
 [ 57 138]
 [ 50 120]
 [ 22  48]
 [ 24  52]
 [ 38  87]
 [ 96 243]
 [ 69 170]
 [ 20  43]
 [ 80 200]
 [ 76 190]
 [ 90 230]
 [ 40  90]
 [ 30  70]
 [ 12  25]
 [ 75 185]
 [ 46 107]
 [ 62 152]
 [ 41  93]
 [ 16  33]
 [ 66 162]
 [ 32  76]
 [ 28  60]
 [ 18  40]
 [ 56 137]
 [ 30  68]
 [ 96 244]
 [ 74 184]
 [ 50 118]
 [ 66 163]
 [ 34  77]
 [ 64 153]
 [ 72 180]
 [ 52 122]
 [ 69 169]
 [ 82 207]
 [ 28  62]
 [ 48 113]

In [127]:
model = LinearRegression()
model.fit(arr_x,arr_y)
model.score(arr_x,arr_y)

0.22240913637907833

In [139]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=20, random_state=100)
rf.fit(arr_x, arr_y)
rf.score(arr_x,arr_y)

0.8719483550708548

In [144]:

rf.predict([[22, 45]])

array([11.1775])